"""empty message

Revision ID: 36ac132df431
Revises: 4ee753e69245
Create Date: 2019-11-05 21:26:35.283786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ac132df431'
down_revision = '4ee753e69245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('latitude', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('postcode', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'postcode')
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    # ### end Alembic commands ###
