"""empty message

Revision ID: 4fe14e5d0346
Revises: 36ac132df431
Create Date: 2019-11-05 21:43:08.814991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fe14e5d0346'
down_revision = '36ac132df431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('long', sa.Float(), nullable=True))
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('latitude', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('longitude', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'long')
    op.drop_column('users', 'lat')
    # ### end Alembic commands ###
