"""empty message

Revision ID: 8f5200fe2553
Revises: 30bb72af3b1f
Create Date: 2019-11-04 13:41:15.140370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f5200fe2553'
down_revision = '30bb72af3b1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'items', 'users', ['owner_id'], ['id'])
    op.drop_column('items', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'owner_id')
    # ### end Alembic commands ###
