"""empty message

Revision ID: bc0527db5f4c
Revises: 6bf380594df5
Create Date: 2019-11-01 12:39:13.771962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0527db5f4c'
down_revision = '6bf380594df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('available', sa.Boolean(), nullable=True))
    op.add_column('items', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_constraint('items_email_key', 'items', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('items_email_key', 'items', ['email'])
    op.drop_column('items', 'created_at')
    op.drop_column('items', 'available')
    # ### end Alembic commands ###
