"""empty message

Revision ID: da51028a7e91
Revises: 23adf5020e95
Create Date: 2019-11-06 09:57:07.682735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da51028a7e91'
down_revision = '23adf5020e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'longitude')
    op.drop_column('items', 'latitude')
    # ### end Alembic commands ###
